spring.application.name=spring-boot-practice
server.port=9090
server.servlet.context-path=/api
logging.level.com.example = DEBUG
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always